[[path]]
start = "N"
end = "SW"

[[path]]
start = "NE"
end = "S"

[[stop]]
position = [-0.08, 0.3, 0.3]
text_id = 1
revenue_angle = 10

[[stop]]
position = [0.08, -0.3, -0.3]
text_id = 1
revenue_angle = -170
