[[path]]
start = "S"
end_pos = [0.0, -0.5, 0.0]

[[path]]
start = "N"
end_pos = [0.0, 0.5, 0.0]

[[city]]
circles = 1
pos = [0.0, -0.5, 0.0]
revenue = 20

[[city]]
circles = 1
pos = [0.0, 0.5, 0.0]
revenue = 20
