[[path]]
start = "S"
end_pos = [0.0, -0.5, 0.0]

[[path]]
start = "N"
end_pos = [0.0, 0.5, 0.0]

[[city]]
text_id = 1
revenue_pos = [-0.6, 0.0, 0.0]
circles = 1
pos = [0.0, -0.5, 0.0]

[[city]]
text_id = 1
revenue_pos = [0.6, 0.0, 0.0]
circles = 1
pos = [0.0, 0.5, 0.0]
