code_text_id = 2
code_position = [0.0, 0.3, 0.3]

[[path]]
start = "NW"
end = "NE"

[[path]]
start = "NW"
end = "S"

[[path]]
start = "NE"
end = "S"

[[stop]]
text_id = 1
revenue_angle = -90
position = [0.0, 0.17, 0.17]
