code_text_id = 2
code_position = [-0.3, -0.4, 0.0]

[[path]]
start = "NW"
end = "C"

[[path]]
start = "S"
end = "C"

[[path]]
start = "NE"
end = "C"

[[city]]
text_id = 1
revenue_pos = [0.0, 0.6, 0.0]
position = "C"
circles = 1
