[[path]]
start = "N"
end = "S"

[[path]]
start = "NE"
end = "SE"

[[stop]]
text_id = 1
revenue_angle = 180
position = [0.0, 0.3, 0.3]

[[stop]]
position = [0.6, -0.17, -0.1]
text_id = 1
revenue_angle = -135
