code_text_id = 2
code_position = [0.5, 0.0, 0.0]

[[path]]
start = "NW"
end_pos = [0.0, 0.0, 0.5]

[[path]]
start = "SW"
end_pos = [0.0, -0.3, 0.3]

[[path]]
start = "S"
end_pos = [0.0, 0.0, -0.5]

[[city]]
circles = 1
pos = [0.1, 0.0, 0.5]
text_id = 1
revenue_pos = [0.0, 0.6, 0.0]
hide_revenue = true

[[city]]
circles = 1
pos = [-0.2, -0.2, 0.0]
text_id = 1
revenue_pos = [0.0, 0.6, 0.0]
hide_revenue = true

[[city]]
circles = 1
pos = [0.0, 0.1, -0.5]
text_id = 1
revenue_pos = [0.0, 0.6, 0.0]
