[[path]]
start = "N"
end = "NW"

[[path]]
start = "NW"
end = "S"

[[path]]
start = "N"
end = "S"

[[path]]
start = "NE"
end = "SW"
is_bridge = true

[[path]]
start = "NE"
end = "SE"
is_bridge = true

[[path]]
start = "SW"
end = "SE"
is_bridge = true

# Double paths to remove white lines going through junction
[[path]]
start = "NE"
end = "SW"

[[path]]
start = "NE"
end = "SE"
