is_lawson = true

[[path]]
start = "N"
end = "S"

[[path]]
start = "NW"
end = "SE"
is_bridge = true

[[path]]
start = "NE"
end = "SW"
is_bridge = true

# Remove white line running through junction
[[path]]
start = "NW"
end = "SE"
