code_text_id = 2
code_position = [0.05, 0.4, 0.0]

[[path]]
start = "NW"
end = "S"

[[path]]
start = "SW"
end = "SE"
is_bridge = true

[[city]]
circles = 1
pos = [-0.3, 0.0, 0.2]
text_id = 1
revenue_pos = [-0.1, 0.35, 0.35]

[[city]]
circles = 1
pos = [0.2, 0.0, -0.3]
text_id = 1
revenue_pos = [0.35, 0.35, -0.1]
