[[path]]
start = "N"
end = "SW"

[[path]]
start = "NE"
end = "S"

[[city]]
circles = 1
pos = [-0.3, -0.3, 0.05]
text_id = 1
revenue_pos = [-0.35, 0.0, 0.35]

[[city]]
circles = 1
pos = [0.3, 0.3, -0.05]
text_id = 1
revenue_pos = [0.35, 0.0, -0.35]
