[[path]]
start = "N"
end_pos = [0.0, 0.3, 0.3]

[[path]]
start = "NW"
end = "NE"

[[path]]
start = "SW"
end = "SE"

[[path]]
start = "S"
end_pos = [0.0, -0.3, -0.3]

[[city]]
text_id = 1
revenue_pos = [0.0, -0.8, 0.1]
circles = 1
pos = [0.0, -0.25, -0.25]

[[city]]
text_id = 1
revenue_pos = [0.7, 0.0, 0.0]
circles = 2
pos = [0.0, 0.25, 0.25]
