code_text_id = 2
code_position = [0.0, 0.0, 0.7]

[[path]]
start = "NW"
end = "C"

[[path]]
start = "SW"
end = "C"

[[path]]
start = "S"
end = "C"

[[city]]
circles = 3
position = "C"
text_id = 1
revenue_pos = [-0.0, 0.8, 0.0]
