code_text_id = 2
code_position = [0.0, 0.0, 0.6]

[[path]]
start = "N"
end = "S"

[[path]]
start = "NW"
end = "SW"

[[path]]
start = "NE"
end = "SE"

[[city]]
circles = 1
pos = [0.5, 0.0, 0.0]
revenue_pos = [0.0, 0.6, 0.0]
text_id = 1

[[city]]
circles = 1
pos = [-0.5, 0.0, 0.0]
revenue_pos = [0.0, 0.6, 0.0]
text_id = 1

[[city]]
circles = 1
pos = [0.0, -0.2, -0.2]
revenue_pos = [0.0, 0.6, 0.0]
text_id = 1
