[[path]]
start = "NE"
end_pos = [0.0, 0.7, 0.0]

[[path]]
start = "S"
end_pos = [0.0, -0.7, 0.0]

[[city]]
revenue = 10
circles = 1
pos = [0.0, 0.5, 0.0]

[[city]]
revenue = 10
circles = 1
pos = [0.0, -0.5, 0.0]
