[[path]]
start = "NE"
end_pos = [0.0, 0.7, 0.0]

[[path]]
start = "S"
end_pos = [0.0, -0.7, 0.0]

[[city]]
circles = 1
pos = [0.0, 0.5, 0.0]
text_id = 1
revenue_pos = [0.0, 0.0, 0.6]

[[city]]
circles = 1
pos = [0.0, -0.5, 0.0]
text_id = 1
revenue_pos = [-0.6, 0.0, 0.0]
