[[path]]
start = "N"
end = "NW"

[[path]]
start = "SW"
end = "S"

[[city]]
text_id = 1
revenue_pos = [0.1, 0.5, 0.0]
circles = 1
pos = [0.0, 0.0, 0.5]

[[city]]
text_id = 1
revenue_pos = [0.1, 0.0, -0.5]
circles = 1
pos = [0.0, -0.5, 0.0]
