[[path]]
start = "N"
end = "S"

[[path]]
start = "NW"
end = "SE"
is_bridge = true

[[stop]]
text_id = 1
position = [-0.3, 0.0, 0.3]
revenue_angle = -90

[[stop]]
text_id = 1
position = [0.0, 0.3, 0.3]
revenue_angle = 0
