[[path]]
start = "NE"
end = "S"

[[path]]
start = "SE"
end = "SW"
is_bridge = true

[[stop]]
text_id = 1
revenue_angle = 110
position = [-0.3, -0.3, -0.08]

[[stop]]
text_id = 1
revenue_angle = 130
position = [0.3, 0.3, -0.08]
