code_text_id = 2
code_position = [-0.3, -0.4, 0.0]

[[path]]
start = "N"
end = "S"

[[path]]
start = "NW"
end = "C"

[[path]]
start = "NE"
end = "C"

[[city]]
position = "C"
circles = 1
text_id = 1
revenue_pos = [0.0, 0.6, 0.0]
