code_position = [0.0, -0.05, -0.05]
code_text_id = 2

[[path]]
start = "N"
end = "NW"

[[path]]
start = "SW"
end = "S"

[[city]]
text_id = 1
revenue_pos = [-0.7, 0.0, 0.0]
circles = 2
pos = [0.0, 0.23, 0.23]

[[city]]
text_id = 1
revenue_pos = [0.7, 0.0, 0.0]
circles = 2
pos = [0.0, -0.23, -0.23]
