[[path]]
start = "N"
end = "NW"

[[path]]
start = "NE"
end = "S"

[[stop]]
position = [0.08, -0.3, -0.3]
text_id = 1
revenue_angle = 170

[[stop]]
position = [0.0, 0.0, 0.5]
text_id = 1
revenue_angle = -30
