[[path]]
start = "NW"
end = "SW"

[[path]]
start = "S"
end = "SE"

[[stop]]
position = [-0.6, 0.17, 0.1]
text_id = 1
revenue_angle = 30

[[stop]]
position = [0.1, 0.17, -0.6]
text_id = 1
revenue_angle = 90
