[[path]]
start = "NW"
end = "SW"

[[path]]
start = "NE"
end = "SE"

[[stop]]
position = [-0.6, 0.17, 0.1]
text_id = 1
revenue_angle = 30

[[stop]]
position = [0.6, -0.17, -0.1]
text_id = 1
revenue_angle = -150
