[[path]]
start = "N"
end = "NE"

[[path]]
start = "NW"
end = "S"

[[city]]
text_id = 1
revenue_pos = [0.0, 0.0, 0.6]
circles = 1
pos = [0.0, 0.5, 0.0]

[[city]]
text_id = 1
revenue_pos = [-0.6, -0.1, 0.0]
circles = 1
pos = [-0.15, -0.2, -0.2]
