[[path]]
start = "S"
end = "N"

[[path]]
start = "NW"
end = "SW"

[[city]]
text_id = 1
revenue_pos = [0.0, -0.7, 0.0]
circles = 1
pos = [-0.5, -0.07, -0.07]

[[city]]
text_id = 1
revenue_pos = [0.35, 0.4, 0.0]
circles = 1
pos = [0.0, 0.25, 0.25]
