[[path]]
start = "S"
end = "N"

[[path]]
start = "SE"
end = "SW"
is_bridge = true

[[city]]
text_id = 1
revenue_pos = [-0.45, 0.0, 0.3]
circles = 1
pos = [-0.43, -0.15, -0.15]

[[city]]
text_id = 1
revenue_pos = [0.23, 0.55, 0.0]
circles = 1
pos = [0.0, 0.25, 0.25]
