[[path]]
start = "S"
end = "N"

[[path]]
start = "SE"
end = "NW"
is_bridge = true

[[city]]
text_id = 1
revenue_pos = [0.3, 0.4, 0.0]
circles = 1
pos = [0.43, -0.05, -0.15]

[[city]]
text_id = 1
revenue_pos = [-0.5, -0.25, 0.0]
circles = 1
pos = [-0.15, -0.28, -0.28]
