[[path]]
start = "N"
end = "S"
stops = 1
revenue = 10

[[path]]
start = "SW"
end = "SE"
is_bridge = true

[[stop]]
text_id = 1
position = [0.0, 0.3, 0.3]
revenue_angle = 180

[[stop]]
text_id = 1
position = [0.3, -0.08, -0.3]
revenue_angle = 60
